# Generated by Django 4.2.7 on 2023-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plowingrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
