# Generated by Django 4.2.7 on 2023-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plowing", "0002_alter_plowingrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="plowingservice",
            name="name",
            field=models.CharField(default="Plowing Service", max_length=255),
        ),
    ]
